export const EnvParam = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  ADMIN_PORT: 'ADMIN_PORT',

  PUBLIC_URL: 'PUBLIC_URL',

  MONGO_URI: 'MONGO_URI',

  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',

  UPLOAD_DIR: 'UPLOAD_DIR',
  MAX_UPLOAD_SIZE_MB: 'MAX_UPLOAD_SIZE_MB',
  UPLOAD_TTL_DAYS: 'UPLOAD_TTL_DAYS',

  GITHUB_REPO_URL: 'GITHUB_REPO_URL',
  GITHUB_BRANCH: 'GITHUB_BRANCH',
  GITHUB_TOKEN: 'GITHUB_TOKEN',
  UPDATE_SECRET_KEY: 'UPDATE_SECRET_KEY',

  GOOGLE_DRIVE_API_KEY: 'GOOGLE_DRIVE_API_KEY',

  YT_CACHE_DIR: 'YT_CACHE_DIR',
  THUMB_DIR: 'THUMB_DIR',
} as const
